### ISSUE TITLE
--open-emulator not working since webpack 5.0

### ISSUE THREAD

**Issue by XaverB** [signageos/webpack-plugin#25]
Dear Sir or Madam,

we upgradet our signageOs application to use webpack 5.73.0 and @signageos/webpack-plugin 0.3.0.
Since the upgrade we can't start the webpack-dev-server with the --open-emulator flag anymore.

package.json
` "scripts": {
    "start": "webpack-dev-server --mode development --open-emulator --watch -d --inline",
...
`

Error: Unknown option '--open-emulator'

**Comment by misak113** [comment]
Hi, you can freely remove the argument. It was never effective and since the new webpavk 5, it's not allowed. It doesn't affect the plugin anyhow.
